### PR TITLE
{TSO,RFSC}TraceBuilder: Don't segfault on NondetError on spawn

### PR DESCRIPTION
**Pull request by margnus1**
What happens here is tricky. When record_symbolic generates an error, interpreter won't create the new thread, but it was still created by TraceBuilder. Thus, the scheduler may choose to execute this nonexistent thread, leading to a crash.

### CODE REVIEW

**Comment by margnus1** [comment]
@kostis This fixes the segfault, but not necessarily in the way you'd like. Still, we must fix this first.

**Comment by kostis** [comment]
I am all for merging this - but perhaps we should also add a test that shows the seg-fault without this patch and avoids it with it.

**Comment by margnus1** [comment]
I moved the test to this PR. I trust it is satisfactory

**Comment by kostis** [comment]
Yes, it's good, if we merge this first.
If the tests pass, go ahead and do this.

**Pull request merged**
